### ISSUE TITLE
Missing tag for MICADO backend

### ISSUE THREAD

**Issue by balcse** [micado-eu/micado_development#1]
` image: micadoproject/micado_backend:18.19.1` as specfified in the docker-compose file does not exist (see on [dockerhub](https://hub.docker.com/r/micadoproject/backend/tags))

**Comment by alzeha** [comment]
I'm not quite sure what you mean here. The docker-compose file says 

`image: ghcr.io/micado-eu/micado_backend:${BACKEND_IMAGE_TAG}`

https://github.com/micado-eu/micado_development/blob/d3027e9f3339047181345d72ca98699da2edb3ba/docker-compose.yaml#L298C1-L298C65

and the .env file says 

`BACKEND_IMAGE_TAG=v2.5.0`

https://github.com/micado-eu/micado_development/blob/d3027e9f3339047181345d72ca98699da2edb3ba/.env#L25C1-L25C25

so where does it states 18.19.1?

Moreover: What do we want to write there? I mean, its an example file and we do not want to change the example file every time someone creates a new image. We could just comment in the .env file after the tags:

Change this to an actual tag to avoid unexpected changes in your system

with a link to dockerhup or whatever. Then we can also delete any latest tag as proposed in issue #2

**Comment by gioppoluca** [comment]
I changed in the compose file and removed the example code in the readme since it is misleading and hard to maintaain
